services:
  - type: web
    name: seventic-scraper
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: CHROME_DRIVER
        value: /usr/bin/chromedriver
